version: '2'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_DB=note_db
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    server:
        build: ./server
        container_name: note_server
        command: go run main.go
        volumes:
            - ./server:/app
        working_dir: /app
        ports:
            - "5000:5000"
    client:
        build: ./client
        container_name: note_client
        command: npm start
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./client:/app
            - /app/node_modules
        working_dir: /app
        ports:
            - "3000:3000"
        tty: true
        depends_on: 
            - server
